Fixed: Installation Error
Xerosploit runs with Python2.7, since there is Python version 3, they are conflicting with each other.

Error:
Traceback (most recent call last):
File "/opt/xerosploit/xerosploit.py", line 26, in
from terminaltables import DoubleTable
ImportError: No module named terminaltables